# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=1500)),
                ('fecha', models.DateTimeField()),
                ('visto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_empresa', models.CharField(max_length=60)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=30)),
                ('provincia', models.CharField(choices=[('CO', 'A Coruña'), ('VI', '�lava'), ('AB', 'Albacete'), ('AL', 'Alicante'), ('AM', 'Almer�a'), ('AS', 'Asturia'), ('AV', '�vila'), ('BA', 'Badajoz'), ('BL', 'Baleares'), ('BR', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'C�ceres'), ('CA', 'C�diz'), ('CN', 'Cantabria'), ('CS', 'Castell�n'), ('CR', 'Ciudad Real'), ('CO', 'C�rdoba'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('HU', 'Huelva'), ('HU', 'Huesca'), ('JA', 'Ja�n'), ('LO', 'La Rioja'), ('GC', 'Las Palmas'), ('LE', 'Le�n'), ('LL', 'Lleida'), ('LU', 'Lugo'), ('MD', 'Madrid'), ('MA', 'M�laga'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('OR', 'Ourense'), ('PA', 'Palencia'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Tenerife'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('TA', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('VA', 'Valencia'), ('VL', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('ZR', 'Zaragoza')], max_length=2)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=usuarios.models.get_image_path)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to=usuarios.models.get_image_path)),
                ('receiver_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Mensaje')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sender_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario_perfil',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sigue',
            field=models.ManyToManyField(to='usuarios.Productor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
