# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productor')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sabado'), ('DO', 'Domingo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencias', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Punto_Distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('coordenada', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Productor')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='punto_distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Punto_Distribucion'),
        ),
        migrations.AddField(
            model_name='comentario_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto'),
        ),
    ]
